name: CI on commits

on: 
  push:
    branches: [ master ]
  pull_request:

jobs:
  check_validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 19.x ]
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm run lint:css
      - run: npm run lint:js

  deploy:
    needs: check_validate
    if: github.ref == 'refs/head/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 19.x ]
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          ssh-key: ${{ secrets.DEPLOY }}

  