name: CI on commits

on: 
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 19.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          folder: site
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: npm install
      - run: npm run deploy
