name: CI on commits

on: 
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 19.x ]
    steps:
      - name: Deploy
        with:
          folder: dist
          ssh-key: ${{ secrets.DEPLOY }}
      - run: npm install
      - run: npm run deploy
