name: CI on commits

on: 
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 19.x ]
    steps:
      - uses: actions/checkout@v3
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: npm install
      - run: npm run build
      - run: -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" && npm run deploy
